export const ACTIVE_CROPS_DATA = [
  {
    id: "tomatoes",
    name: "Tomatoes",
    stage: "Flowering",
    daysLeft: 45,
    health: "Excellent",
    temp: "25°C",
    humidity: "65%",
    icon: "leaf-outline",
    bgColor: "#BBECCA",
    plantedDate: "2024-02-15",
    expectedHarvestDate: "2024-04-01",
    lastWatered: "2024-03-10",
    lastFertilized: "2024-03-05",
    soilMoisture: "Optimal",
    lightExposure: "Full Sun",
    notes: "Growing well, flowers starting to form",
  },
  {
    id: "carrots",
    name: "Carrots",
    stage: "Growing",
    daysLeft: 30,
    health: "Good",
    temp: "22°C",
    humidity: "70%",
    icon: "nutrition-outline",
    bgColor: "#B7E6DC",
    plantedDate: "2024-02-20",
    expectedHarvestDate: "2024-03-21",
    lastWatered: "2024-03-10",
    lastFertilized: "2024-03-01",
    soilMoisture: "Slightly Dry",
    lightExposure: "Partial Sun",
    notes: "Root development progressing normally",
  },
  {
    id: "lettuce",
    name: "Lettuce",
    stage: "Seedling",
    daysLeft: 25,
    health: "Good",
    temp: "20°C",
    humidity: "75%",
    icon: "flower-outline",
    bgColor: "#BBECCA",
    plantedDate: "2024-02-25",
    expectedHarvestDate: "2024-03-22",
    lastWatered: "2024-03-10",
    lastFertilized: "2024-02-28",
    soilMoisture: "Moist",
    lightExposure: "Partial Shade",
    notes: "Seedlings showing healthy growth pattern",
  },
  {
    id: "bellPeppers",
    name: "Bell Peppers",
    stage: "Fruiting",
    daysLeft: 35,
    health: "Excellent",
    temp: "24°C",
    humidity: "60%",
    icon: "leaf-outline",
    bgColor: "#B7E6DC",
    plantedDate: "2024-02-18",
    expectedHarvestDate: "2024-03-25",
    lastWatered: "2024-03-10",
    lastFertilized: "2024-03-03",
    soilMoisture: "Optimal",
    lightExposure: "Full Sun",
    notes: "First fruits beginning to form, good color",
  },
  {
    id: "spinach",
    name: "Spinach",
    stage: "Growing",
    daysLeft: 20,
    health: "Good",
    temp: "21°C",
    humidity: "72%",
    icon: "flower-outline",
    bgColor: "#BBECCA",
    plantedDate: "2024-02-28",
    expectedHarvestDate: "2024-03-20",
    lastWatered: "2024-03-10",
    lastFertilized: "2024-03-01",
    soilMoisture: "Moist",
    lightExposure: "Partial Sun",
    notes: "Leaves developing well, rich green color",
  },
];

export default ACTIVE_CROPS_DATA; 