export const CROP_DETAILS = {
  "Tomatoes": {
    name: "Tomatoes",
    scientificName: "Solanum lycopersicum",
    images: [
      "https://images.unsplash.com/photo-1592841200221-a6898f307baa",
      "https://images.unsplash.com/photo-1592475820797-4c4c1884c810",
    ],
    description: "Tomatoes are the edible berry of the plant Solanum lycopersicum. They are a great source of vitamin C, potassium, folate, and vitamin K.",
    growthPeriod: "60-80 days",
    waterRequirements: "Regular - 1-2 inches per week",
    soilType: "Well-draining, slightly acidic",
    climate: "Warm season",
    cultivationSteps: [
      "Start seeds indoors 6-8 weeks before last frost",
      "Transplant when soil warms to 60°F",
      "Space plants 18-36 inches apart",
      "Provide support (cage or stake)",
      "Water deeply and regularly",
    ],
    expectedYield: "20-30 pounds per plant",
    varieties: ["Roma", "Beefsteak", "Cherry", "Heirloom", "Plum"],
    nutritionalValue: {
      calories: "22 per 100g",
      vitamins: ["Vitamin C", "Vitamin K", "Vitamin A"],
      minerals: ["Potassium", "Folate"],
      benefits: ["Heart health", "Eye health", "Cancer prevention"],
    },
  },
  "Bell Peppers": {
    name: "Bell Peppers",
    scientificName: "Capsicum annuum",
    images: [
      "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83",
      "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5",
    ],
    description: "Bell peppers are sweet, crisp vegetables rich in vitamins C and A. They come in various colors as they mature.",
    growthPeriod: "60-90 days",
    waterRequirements: "Moderate - 1 inch per week",
    soilType: "Rich, well-draining soil",
    climate: "Warm season",
    cultivationSteps: [
      "Start seeds indoors 8-10 weeks before last frost",
      "Transplant when soil reaches 65°F",
      "Space plants 18-24 inches apart",
      "Support larger plants with stakes",
      "Maintain consistent moisture",
    ],
    expectedYield: "5-10 peppers per plant",
    varieties: ["California Wonder", "Purple Beauty", "Golden Summer", "Sweet Banana"],
    nutritionalValue: {
      calories: "31 per 100g",
      vitamins: ["Vitamin C", "Vitamin A", "Vitamin B6"],
      minerals: ["Potassium", "Folate"],
      benefits: ["Immune support", "Eye health", "Metabolism"],
    },
  },
  "Lettuce": {
    name: "Lettuce",
    scientificName: "Lactuca sativa",
    images: [
      "https://images.unsplash.com/photo-1622206151246-71f91baa3211",
      "https://images.unsplash.com/photo-1622206150048-03508c8a7b55",
    ],
    description: "Lettuce is a leafy green vegetable that's easy to grow and perfect for salads and sandwiches.",
    growthPeriod: "30-60 days",
    waterRequirements: "Regular - keep soil moist",
    soilType: "Rich, well-draining soil",
    climate: "Cool season",
    cultivationSteps: [
      "Sow seeds directly in garden",
      "Plant 1/4 inch deep",
      "Space plants 6-12 inches apart",
      "Keep soil consistently moist",
      "Harvest outer leaves as needed",
    ],
    expectedYield: "1-2 heads per plant",
    varieties: ["Romaine", "Butterhead", "Iceberg", "Leaf Lettuce"],
    nutritionalValue: {
      calories: "15 per 100g",
      vitamins: ["Vitamin K", "Vitamin A", "Vitamin C"],
      minerals: ["Iron", "Folate"],
      benefits: ["Hydration", "Fiber", "Low calorie"],
    },
  },
  "Carrots": {
    name: "Carrots",
    scientificName: "Daucus carota",
    images: [
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37",
      "https://images.unsplash.com/photo-1598170845145-fa0f8e5bfa2b",
    ],
    description: "Carrots are root vegetables known for their crisp texture and sweet taste. They're excellent sources of beta carotene.",
    growthPeriod: "70-80 days",
    waterRequirements: "Moderate - 1 inch per week",
    soilType: "Deep, loose, well-draining soil",
    climate: "Cool season",
    cultivationSteps: [
      "Sow seeds directly in garden",
      "Plant 1/4 inch deep in rows",
      "Space rows 12-18 inches apart",
      "Thin seedlings to 2-3 inches apart",
      "Keep soil evenly moist",
    ],
    expectedYield: "8-10 carrots per foot",
    varieties: ["Nantes", "Danvers", "Imperator", "Chantenay"],
    nutritionalValue: {
      calories: "41 per 100g",
      vitamins: ["Vitamin A", "Vitamin K", "Vitamin C"],
      minerals: ["Potassium", "Calcium"],
      benefits: ["Eye health", "Immune support", "Heart health"],
    },
  }
};
